#!/usr/bin/env ruby
require 'date'

arguments = ARGV
help = "I'd cheer for you, if only I knew who you were :(\nTry again with `./cheers.rb [Name] [MM/DD Birthday]`"

if arguments.length == 1
  name = arguments[0]
  birthday = ""
elsif arguments.length == 2
  name = arguments[0]
  birthday = arguments[1]
end

def name_parser(name)
  print_name = name
  an_letters = "AEIOU"
  name = name.sub(/-/, '') if /-/.match(name)
  name.each_char do |letter|
    letter.upcase!
    article = an_letters.include?(letter) ? "an" : "a"
    print "Give me #{article}... #{letter}\n"
  end
  print print_name.rstrip + "'s just GRAND!\n"
end

def date_parser(bd)
  if /[a-zA-Z]/.match(bd)
    true
  end
end

def date_finder(bd)
  birthday = Date.parse(bd)
  now = DateTime.now
  current = now.month.to_s << '/' << now.day.to_s
  today = Date.parse(current)

  if (birthday - today) < 0
    days_away = (birthday - today).to_s
    days_away.sub!(/-/, '')
    days_away = days_away.to_i
    puts "\nAwesome! Your birthday was #{days_away} days ago! Happy belated birthday!"
  elsif (birthday - today) > 0
    days_away = (birthday - today).to_i
    puts "\nAwesome! Your birthday is in #{days_away} days! Happy Birthday in advance!"
  end
end

if /[a-zA-Z]/.match(name).nil? or arguments == [] or date_parser(birthday)
  puts help
else
  name_parser(name)
  if birthday != ""
    date_finder(birthday)
  end
end

