#!/usr/bin/env ruby
require 'date'

arguments = ARGV

def puts_help_message
  puts "I'd cheer for you, if only I knew who you were :(\nTry again with `./cheers.rb [Name] [MM/DD Birthday]`"
end

if arguments.length == 1
  name = arguments[0]
  birthday = ""
else
  name = arguments[0]
  birthday = arguments[1]
end

def name_parser(name)
  print_name = name
  an_letters = "AEFHILMNORSX"
  cheer_name = name.upcase.gsub(/[^A-Z]/, '')
  cheer_name.each_char do |letter|
    article = an_letters.include?(letter) ? "an" : "a"
    print "Give me #{article}... #{letter}\n"
  end
  print print_name.rstrip + "'s just GRAND!\n"
end

def date_parser(bd)
  month = bd[0] + bd [1] if bd != ""
  if /[a-zA-Z]/.match(bd) or bd.length > 5 or month.to_i > 12
    true
  end
end

def date_finder(bd)
  birthday = Date.parse(bd)
  now = DateTime.now
  current = now.month.to_s << '/' << now.day.to_s
  today = Date.parse(current)

  if (birthday - today) < 0
    days_away = (birthday - today).to_s
    days_away.sub!(/-/, '')
    days_away = days_away.to_i
    puts "\nAwesome! Your birthday was #{days_away} days ago! Happy belated birthday!"
  elsif (birthday - today) > 0
    days_away = (birthday - today).to_i
    puts "\nAwesome! Your birthday is in #{days_away} days! Happy Birthday in advance!"
  end
end

if /[a-zA-Z]/.match(name).nil? or arguments == [] or date_parser(birthday)
  puts_help_message
else
  name_parser(name)
  if birthday != ""
    date_finder(birthday)
  end
end

